# Generated by Django 6.0.4 on 2026-04-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('em_andamento', 'Em andamento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='agendado', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=11),
        ),
    ]
