<<<<<<< HEAD
# Generated by Django 6.0.4 on 2026-04-14 01:58
=======
# Generated by Django 6.0.4 on 2026-04-16 00:45
>>>>>>> ce52d72 (salvando versão estável antes do deploy)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0002_agendamento_status_alter_cliente_telefone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='status',
            new_name='status_atendimento',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='status_pagamento',
            field=models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente')], default='pendente', max_length=20),
        ),
    ]
